# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_daw.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1061, 617)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.add_pattern_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.add_pattern_btn.setObjectName("add_pattern_btn")
        self.gridLayout_2.addWidget(self.add_pattern_btn, 1, 0, 1, 1)
        self.delete_ptrn_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.delete_ptrn_btn.setObjectName("delete_ptrn_btn")
        self.gridLayout_2.addWidget(self.delete_ptrn_btn, 1, 1, 1, 1)
        self.patternView = QtWidgets.QListWidget(self.groupBox_2)
        self.patternView.setObjectName("patternView")
        self.gridLayout_2.addWidget(self.patternView, 0, 0, 1, 2)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 2)
        self.sequencer_table = QtWidgets.QTableWidget(self.centralwidget)
        self.sequencer_table.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.sequencer_table.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sequencer_table.setMidLineWidth(0)
        self.sequencer_table.setShowGrid(False)
        self.sequencer_table.setGridStyle(QtCore.Qt.NoPen)
        self.sequencer_table.setCornerButtonEnabled(False)
        self.sequencer_table.setRowCount(16)
        self.sequencer_table.setColumnCount(50)
        self.sequencer_table.setObjectName("sequencer_table")
        self.sequencer_table.horizontalHeader().setDefaultSectionSize(90)
        self.sequencer_table.horizontalHeader().setMinimumSectionSize(20)
        self.sequencer_table.verticalHeader().setDefaultSectionSize(30)
        self.sequencer_table.verticalHeader().setMinimumSectionSize(20)
        self.gridLayout_3.addWidget(self.sequencer_table, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setHorizontalSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.channel = QtWidgets.QSpinBox(self.groupBox)
        self.channel.setWrapping(False)
        self.channel.setMinimum(1)
        self.channel.setMaximum(16)
        self.channel.setObjectName("channel")
        self.gridLayout.addWidget(self.channel, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)
        self.openSynth = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.openSynth.setFont(font)
        self.openSynth.setObjectName("openSynth")
        self.gridLayout_3.addWidget(self.openSynth, 1, 1, 1, 1)
        self.play_seq_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_seq_button.setObjectName("play_seq_button")
        self.gridLayout_3.addWidget(self.play_seq_button, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MiLive_1205"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Последовательности нот"))
        self.add_pattern_btn.setText(_translate("MainWindow", "Добавить"))
        self.delete_ptrn_btn.setText(_translate("MainWindow", "Удалить"))
        self.groupBox.setTitle(_translate("MainWindow", "Канал"))
        self.openSynth.setText(_translate("MainWindow", "Открыть синтезатор"))
        self.play_seq_button.setText(_translate("MainWindow", "Играть последовательность"))
