# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sequence_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sequence_creator_window(object):
    def setupUi(self, sequence_creator_window):
        sequence_creator_window.setObjectName("sequence_creator_window")
        sequence_creator_window.resize(934, 476)
        self.gridLayout_2 = QtWidgets.QGridLayout(sequence_creator_window)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.play_sequence = QtWidgets.QPushButton(sequence_creator_window)
        self.play_sequence.setObjectName("play_sequence")
        self.gridLayout_2.addWidget(self.play_sequence, 1, 1, 1, 1)
        self.add_sequence = QtWidgets.QPushButton(sequence_creator_window)
        self.add_sequence.setObjectName("add_sequence")
        self.gridLayout_2.addWidget(self.add_sequence, 1, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(sequence_creator_window)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(96)
        self.tableWidget.setColumnCount(40)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setDefaultSectionSize(45)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(45)
        self.tableWidget.verticalHeader().setDefaultSectionSize(15)
        self.tableWidget.verticalHeader().setMinimumSectionSize(15)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 3)

        self.retranslateUi(sequence_creator_window)
        QtCore.QMetaObject.connectSlotsByName(sequence_creator_window)

    def retranslateUi(self, sequence_creator_window):
        _translate = QtCore.QCoreApplication.translate
        sequence_creator_window.setWindowTitle(_translate("sequence_creator_window", "Создание паттерна"))
        self.play_sequence.setText(_translate("sequence_creator_window", "Проиграть паттерн"))
        self.add_sequence.setText(_translate("sequence_creator_window", "Добавить паттерн"))
        self.groupBox.setTitle(_translate("sequence_creator_window", "Последовательность"))
